# Generated by Django 5.2.1 on 2025-07-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_resume_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="province",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="school_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="languages",
            name="language",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="summary",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
