# Generated by Django 5.0.6 on 2025-01-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resume_contactinfo_resume_education_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='full_name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='l_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
