# Generated by Django 5.0.6 on 2025-01-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_full_name_contactinfo_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='graduation_date',
            new_name='graduation_year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='city',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date',
            new_name='start_year',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='end_date',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='city',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='start_date',
            new_name='start_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='province',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='province',
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_month',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
