# Generated by Django 5.0.6 on 2025-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_graduation_date_education_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
