# Generated by Django 5.0.6 on 2025-01-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_education_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedescription',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='employer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
