# Generated by Django 5.0.6 on 2025-01-27 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_experiencedescription_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedescription',
            name='work',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workexperience'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
