# Generated by Django 5.0.6 on 2025-01-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_experiencedescription_work_alter_skills_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summery',
            new_name='Summary',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='summery',
            new_name='summary',
        ),
    ]
